version: "3.8"
services:
  postgres:
    image: postgres:16.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    # container_name: medusa-postgres
    volumes:
      - ./medusa/docker/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    # container_name: medusa-redis